#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import os
import glob
import json
import argparse
from collections import OrderedDict

def get_score_from_data(data, score_field=None):
    if score_field is not None:
        if score_field in data and data[score_field] != "":
            return float(data[score_field])
        if 'graph_global_score' in data and isinstance(data['graph_global_score'], dict):
            if score_field in data['graph_global_score'] and data['graph_global_score'][score_field] != "":
                return float(data['graph_global_score'][score_field])
        available_fields = list(data.keys())
        if 'graph_global_score' in data and isinstance(data['graph_global_score'], dict):
            available_fields.extend(['graph_global_score.' + k for k in data['graph_global_score'].keys()])
        raise ValueError(f"Score field '{score_field}' not found. Available fields: {available_fields}")

    if 'global_score_qu' in data and data['global_score_qu'] != "":
        return float(data['global_score_qu'])
    elif 'global_score_md' in data and data['global_score_md'] != "":
        return float(data['global_score_md'])
    elif 'global_score' in data and data['global_score'] != "":
        return float(data['global_score'])

    return None

def main():
    parser = argparse.ArgumentParser(
        description="Generate CSV file from MetaScreener results"
    )
    parser.add_argument("experiment_folder", type=str,
                        help="Path to folder generated by MetaScreener")
    parser.add_argument("--score-field", type=str, default=None,
                        help="Custom score field name for ranking")
    parser.add_argument("--score-ascending", type=str, default="true",
                        help="Score order: true (lower is better) or false (higher is better)")

    args = parser.parse_args()

    # Interpret score-ascending
    if args.score_ascending.lower() in ['false', '0', 'no', 'n', 'off']:
        score_ascending = False
    elif args.score_ascending.lower() in ['true', '1', 'yes', 'y', 'on']:
        score_ascending = True
    else:
        print("ERROR: Invalid value for --score-ascending. Use true/false.")
        sys.exit(2)

    directory = os.path.abspath(args.experiment_folder)
    score_field = args.score_field

    if not os.path.isdir(directory):
        print(f"Error: Directory '{directory}' does not exist")
        sys.exit(1)

    # Detect energies/ or fallback to results/
    json_dir = os.path.join(directory, "energies")
    json_pattern = "*.json"
    if not os.path.isdir(json_dir):
        json_dir = os.path.join(directory, "results")
        json_pattern = "*[0-9].json"

    json_files_pattern = os.path.join(json_dir, json_pattern)
    print(f"📂 Searching for JSON files in: {json_files_pattern}")

    data = {}
    cnt_json = 0

    for f_json in glob.glob(json_files_pattern):
        try:
            with open(f_json, 'r') as f:
                d = json.load(f)

            score = get_score_from_data(d, score_field)

            if score is not None:
                data[cnt_json] = [
                    score,
                    float(d['coords'][0]),
                    float(d['coords'][1]),
                    float(d['coords'][2]),
                    os.path.splitext(os.path.basename(d['file_ori_query']))[0],
                    int(d['num_execution']),
                    os.path.abspath(f_json)
                ]
                cnt_json += 1

        except (KeyError, ValueError, TypeError, FileNotFoundError, json.JSONDecodeError) as e:
            print(f"⚠️  Skipping file {f_json}: {e}")
            continue

    # Sort results
    data = OrderedDict(sorted(data.items(), key=lambda t: t[1][0], reverse=not score_ascending))

    # Output file
    output_file = os.path.join(directory, "Results_scoring.csv")
    header = f"{score_field if score_field else 'Global score'};x;y;z;Querie;Num_execution;Path\n"

    try:
        with open(output_file, "w") as file:
            file.write(header)
            for _, row in data.items():
                file.write(";".join(str(x) for x in row) + "\n")

        print(f"\n✅ CSV generated: {output_file}")
        print(f"📊 Ligands processed: {len(data)}")
        if score_field:
            print(f"🔧 Custom scoring field: {score_field}")
        print(f"⬆️ Score order: {'Lower is better' if score_ascending else 'Higher is better'}")

    except IOError as e:
        print(f"❌ Error writing CSV file: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
