#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import glob
import json
import os
import getopt
from collections import OrderedDict

def usage():
    print("")
    print("Generate CSV file from MetaScreener results")
    print("")
    print("Usage:")
    print("  get_csv.py <experiment_folder> [options]")
    print("")
    print("Required arguments:")
    print("  experiment_folder    Path to folder generated by MetaScreener")
    print("")
    print("Optional arguments:")
    print("  --score-field        Custom score field name for ranking")
    print("  --score-ascending    Score order: true (lower is better) or false (higher is better)")
    print("                       Default: true")
    print("  -h, --help          Show this help message")
    print("")
    print("Examples:")
    print("  get_csv.py BD_AD_1le0_GLA_2018-07-25/")
    print("  get_csv.py BD_GN_1le0_GLA_2018-07-25/ --score-field CNNscore --score-ascending false")
    print("")

def get_score_from_data(data, score_field=None):
    """
    Extract score from JSON data using custom field or default hierarchy
    """
    if score_field is not None:
        # Try direct field access
        if score_field in data and data[score_field] != "":
            return float(data[score_field])
        
        # Try graph_global_score decomposition
        if 'graph_global_score' in data and isinstance(data['graph_global_score'], dict):
            if score_field in data['graph_global_score'] and data['graph_global_score'][score_field] != "":
                return float(data['graph_global_score'][score_field])
        
        # If custom field not found, raise error
        available_fields = list(data.keys())
        if 'graph_global_score' in data and isinstance(data['graph_global_score'], dict):
            available_fields.extend(['graph_global_score.' + k for k in data['graph_global_score'].keys()])
        raise ValueError("Score field '{}' not found. Available fields: {}".format(score_field, available_fields))
    
    # Default hierarchy: global_score_qu > global_score_md > global_score
    if 'global_score_qu' in data and data['global_score_qu'] != "":
        return float(data['global_score_qu'])
    elif 'global_score_md' in data and data['global_score_md'] != "":
        return float(data['global_score_md'])
    elif 'global_score' in data and data['global_score'] != "":
        return float(data['global_score'])
    
    return None

def main():
    # Parse command line arguments
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help", "score-field=", "score-ascending="])
    except getopt.GetoptError as err:
        print("Error: {}".format(err))
        usage()
        sys.exit(2)
    
    score_field = None
    score_ascending = True
    
    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit()
        elif o == "--score-field":
            score_field = a
        elif o == "--score-ascending":
            if a.lower() in ['true', '1', 'yes', 'y', 'on']:
                score_ascending = True
            elif a.lower() in ['false', '0', 'no', 'n', 'off']:
                score_ascending = False
            else:
                print("ERROR: Invalid value for --score-ascending. Use true/false.")
                sys.exit(2)
    
    # Check required arguments
    if len(args) != 1:
        print("Error: Must specify exactly one experiment folder")
        usage()
        sys.exit(2)
    
    directory = args[0]
    
    # Validate directory
    if not os.path.isdir(directory):
        print("Error: Directory '{}' does not exist".format(directory))
        sys.exit(1)
    
    data = {}
    cnt_json = 0
    json_files = "/energies/*.json"
    
    if not os.path.isdir(directory + "/energies/"):
        json_files = "/results/*[0-9].json"
    
    for f_json in glob.glob(directory + json_files):
        try:
            with open(f_json) as f:
                d = json.load(f)
            
            # Get score using custom field or default hierarchy
            score = get_score_from_data(d, score_field)
            
            if score is not None:
                data[cnt_json] = [
                    score,
                    float(d['coords'][0]),
                    float(d['coords'][1]),
                    float(d['coords'][2]),
                    str(os.path.splitext(os.path.basename(d['file_ori_query']))[0]),
                    int(d['num_execution']),
                    str(os.path.splitext((os.path.abspath(f_json)))[0])
                ]
                cnt_json += 1
                
        except (KeyError, ValueError, TypeError) as e:
            print("Warning: Skipping file {} due to error: {}".format(f_json, e))
            continue
    
    # Sort data based on score_ascending parameter
    if score_ascending:
        # Lower scores are better (default behavior)
        data = OrderedDict(sorted(data.items(), key=lambda t: t[1][0]))
    else:
        # Higher scores are better
        data = OrderedDict(sorted(data.items(), key=lambda t: t[1][0], reverse=True))
    
    # Write CSV file
    output_file = os.path.join(directory, "Results_scoring.csv")
    
    # Determine header based on scoring method
    if score_field:
        header = "{};x;y;z;Querie;Num_execution;Path\n".format(score_field)
    else:
        header = "Global score;x;y;z;Querie;Num_execution;Path\n"
    
    try:
        with open(output_file, "w") as file:
            file.write(header)
            for i, k in data.items():
                file.write(str(k)[1:-1].replace(', ', ';').replace("'", "") + "\n")
        
        print("CSV file generated successfully: {}".format(output_file))
        print("Total ligands processed: {}".format(len(data)))
        if score_field:
            print("Custom scoring field used: {}".format(score_field))
            print("Score order: {} is better".format("Lower" if score_ascending else "Higher"))
        
    except IOError as e:
        print("Error writing CSV file: {}".format(e))
        sys.exit(1)

if __name__ == "__main__":
    main()
