import sys
import glob
import json
import os
from collections import OrderedDict

if len(sys.argv) != 2:
    print("")
    print("Must indicate a folder generated by Metascreener for example:")
    print("print  MetaScreener/extra_metascreener/get_csv.py BD_AD_1le0_GLA_2018-07-25/")
    print ("")
    exit()

data={}
cnt_json=0
directory = sys.argv[1]
for f_json in glob.glob(directory+"/energies/*.json"):
    with open(f_json) as f:
        d = json.load(f)
    data [cnt_json] = [ float( d['global_score'] ),float(d['coords'][0]),float(d['coords'][1]),float(d['coords'][2]),str(d['file_ori_query']),int(d['num_execution']) ]
    cnt_json += 1
data=OrderedDict(sorted(data.items(), key=lambda t: t[1][0]))
file = open(os.path.join(directory+"/Resume.csv"), "w")
file.write("Global score;x;y;z;Querie;Num_execution\n")
for i, k in data.items():
    file.write(str(k)[1:-1].replace(', ', ';')+"\n")
file.close()